export * from './ViewBottomCenter';
export * from './ViewBottomLeft';
export * from './ViewWrk';
export * from './ViewWelcome';
export * from './ViewCenterLeft';
export * from './ViewCenterRight';
export * from './ViewTopCenter';
export * from './ViewAbout';
export * from './ViewTopRight';
